change msg template and add key value check
Rogggger/WeChatterBot pull request #23
Opened 2020-05-07 15:47 UTC by G1NTOKI0522

change REPLY_STR template; 
add key value check in post request handle; 
add reply to Event Msg

2020-05-07 15:52 UTC, Rogggger requested changes

2020-05-07 15:52 UTC, Rogggger commented on app/view/wechat.py
> +
这个换行貌似没必要？
```suggestion
```

2020-05-07 15:57 UTC, G1NTOKI0522 commented on app/view/wechat.py
> +
唔的确没必要

2020-05-08 03:25 UTC, Rogggger requested changes
另外记得把机器人提出的错误改了

2020-05-08 03:25 UTC, Rogggger commented on app/view/wechat.py
> +        if not all(k in req for k in check_keys):
这句判断貌似并不能达到想要的效果，只判断了键是否在字典里

2020-05-08 03:25 UTC, Rogggger commented on app/view/wechat.py
> +        if not all(k in req for k in check_keys):
应该确定的是里面内容是否有值

2020-05-08 06:19 UTC, Rogggger requested changes

2020-05-08 06:19 UTC, Rogggger commented on app/view/wechat.py
> +            return error_jsonify(10000001)
这句`if not all(k in req for k in check_keys):`应该是没有意义的，因为它检查`'MsgType', 'Content'`这两个键在`req`中的存在，然而`req`是由生成式`req = {k: xml_rec.find(k) for k in MSG_KEYS}`生成的，它必包含这两个键。这里应该做的是下面的，对`req`中的值进行判断的操作：
```suggestion
        if not all(req[k] is not None for k in check_keys):
            return error_jsonify(10000001)
        if req['MsgType'] == 'event':  # 接收事件推送
            req['Content'] = xml_rec.find('Event')
```
而且你以前写的逻辑相当于，如果MegType不是event，那就直接返回错误了

2020-05-08 06:26 UTC, G1NTOKI0522 commented on app/view/wechat.py
> +            return error_jsonify(10000001)
Event类型消息的xml没有Content键，两个应该结合起来写，i get

2020-05-08 06:29 UTC, Rogggger commented on app/view/wechat.py
> +            return error_jsonify(10000001)
我大概猜到了，那即使这样的话，你也可以先判断MsgType的值，对Content赋值之后再使用上面的那个if判断。把我这两句if对调即可

2020-05-08 07:00 UTC, Rogggger requested changes

2020-05-08 07:00 UTC, Rogggger commented on app/view/wechat.py
> +            return error_jsonify(10000001)
```suggestion
        if req['MsgType'] is None:
            return error_jsonify(10000001)
        if req['MsgType'] == 'event':
            req['Content'] = xml_rec.find('Event')
        if req['Content'] is None:
            return error_jsonify(10000001)
```
这样你觉得如何

2020-05-08 07:07 UTC, G1NTOKI0522 commented on app/view/wechat.py
> +            return error_jsonify(10000001)
觉得非常可

2020-05-08 07:10 UTC, Rogggger approved these changes
LGTM

2020-05-08 07:11 UTC, merged